/* ============ BASE D EXERCICES ============ */
const DB={
 'pompes-poignees':{nom:'Pompes',en:'Push-ups',mus:'Pectoraux, triceps, épaules',type:'reps',start:20,inc:2,series:'3 séries (ex : 8 / 6 / 6), repos 60 s',
  desc:['Mains au sol largeur épaules, ou sur les poignées si tu en as, corps gainé en planche des épaules aux talons.','Descends en 2 s, poitrine entre les mains, coudes à ~45° du corps (pas collés, pas à 90°).','Remonte en poussant fort et en soufflant, sans casser la ligne du corps.'],
  vig:'<b>Dos :</b> serre abdos et fessiers, ne laisse jamais le bassin s\'affaisser. <b>Cou :</b> regard au sol légèrement devant, nuque neutre.',
  fin:'l\'affaissement du bassin, jamais l\'épuisement des pectoraux. Une pompe de plus la ligne cassée n\'est pas une pompe de plus, c\'est une extension lombaire sous charge.',
  fig:{a:{hd:[22,56],nk:[33,61],hp:[68,66],kf:[85,70],ff:[104,90],ea:[33,75],ha:[31,89],props:[{t:'bar',at:[24,90],to:[40,90]}]},b:{hd:[20,72],nk:[31,76],hp:[67,74],kf:[85,76],ff:[104,90],ea:[42,86],ha:[31,89],props:[{t:'bar',at:[24,90],to:[40,90]}]}},
  fb:'pompes-inclinees'},
 'pompes-inclinees':{nom:'Pompes inclinées',en:'Incline push-ups',mus:'Pectoraux, triceps',type:'reps',start:24,inc:2,series:'3 séries, repos 45 s',
  desc:['Mains sur un support stable (table, plan de travail), corps en planche inclinée.','Même mouvement que la pompe classique, souffle en remontant, charge réduite sur épaules et poignets.'],
  vig:'Version de repli douce pour les épaules. Garde quand même le gainage.',
  fig:{a:{hd:[34,30],nk:[43,37],hp:[72,58],kf:[86,70],ff:[100,89],ea:[42,50],ha:[40,62],props:[{t:'box',at:[28,62],w:18,h:31}]},b:{hd:[27,40],nk:[36,46],hp:[68,62],kf:[84,72],ff:[100,89],ea:[40,56],ha:[40,62],props:[{t:'box',at:[28,62],w:18,h:31}]}}},
 'elevations-laterales':{nom:'Élévations latérales',en:'Lateral raises',mus:'Épaules (deltoïdes)',type:'reps',start:30,inc:2,series:'3 séries de 10, haltères légers (1-2 kg)',
  desc:['Debout, un haltère léger dans chaque main le long du corps, coudes très légèrement fléchis.','Monte les bras sur les côtés en soufflant, jusqu\'à l\'horizontale, pas plus haut, en 2 s.','Redescends lentement en 2-3 s : c\'est la descente qui travaille le plus.'],
  vig:'<b>Cou/épaules :</b> épaules basses, ne hausse pas les trapèzes. Si ça tire dans le cou, réduis l\'amplitude ou le poids.',
  fin:'le balancier. Dès que les jambes ou le dos donnent l\'élan pour monter les bras, ce n\'est plus une élévation latérale.',
  fig:{a:{hd:[60,22],nk:[60,32],hp:[60,58],kf:[54,75],ff:[52,91],kb:[66,75],fb:[68,91],ea:[52,44],ha:[48,54],eb:[68,44],hb:[72,54],props:[{t:'db',at:[48,56]},{t:'db',at:[72,56]}]},b:{hd:[60,22],nk:[60,32],hp:[60,58],kf:[54,75],ff:[52,91],kb:[66,75],fb:[68,91],ea:[46,34],ha:[34,33],eb:[74,34],hb:[86,33],props:[{t:'db',at:[32,33]},{t:'db',at:[88,33]}]}},
  fb:'tirage-doux'},
 'face-pulls':{nom:'Face pulls à l\'élastique',en:'Face pulls',mus:'Arrière d\'épaules, fixateurs d\'omoplates',type:'reps',start:36,inc:3,series:'3 séries de 12, tension modérée',
  desc:['Élastique fixé à hauteur de visage : ancrage de porte en haut de porte, ou barre de traction.','Bras tendus devant toi, tire l\'élastique vers ton visage en écartant les coudes.','Finis coudes hauts, mains de chaque côté de la tête, omoplates serrées. Souffle en tirant, inspire au retour.'],
  vig:'<b>C\'est ton exercice santé n°1</b> pour le cou et les épaules : privilégie la qualité, jamais d\'à-coups.',
  fig:{a:{hd:[46,26],nk:[48,36],hp:[46,60],kf:[42,76],ff:[40,91],kb:[52,76],fb:[54,91],ea:[62,38],ha:[76,36],props:[{t:'band',at:[76,36],to:[104,30]}]},b:{hd:[44,26],nk:[46,36],hp:[45,60],kf:[41,76],ff:[39,91],kb:[51,76],fb:[53,91],ea:[58,28],ha:[54,36],props:[{t:'band',at:[54,36],to:[104,30]}]}},
  fb:'tirage-doux'},
 'tirage-doux':{nom:'Tirage élastique doux',en:'Easy band pull',mus:'Haut du dos',type:'reps',start:30,inc:2,series:'3 séries, tension faible',
  desc:['Élastique de faible tension, tire vers toi coudes le long du corps en soufflant, amplitude confortable.','Objectif du jour : bouger sans douleur, pas performer.'],
  vig:'Version de repli. Reste dans une amplitude 100 % indolore.',
  fig:{a:{hd:[46,26],nk:[48,36],hp:[46,60],kf:[42,76],ff:[40,91],kb:[52,76],fb:[54,91],ea:[60,44],ha:[74,44],props:[{t:'band',at:[74,44],to:[104,40]}]},b:{hd:[46,26],nk:[48,36],hp:[46,60],kf:[42,76],ff:[40,91],kb:[52,76],fb:[54,91],ea:[58,48],ha:[56,52],props:[{t:'band',at:[56,52],to:[104,40]}]}}},
 'developpe-sol':{nom:'Développé haltères au sol',en:'Dumbbell floor press',mus:'Pectoraux, triceps',type:'reps',start:16,inc:2,series:'3 séries de 8, montée verticale',
  desc:['Assis au sol, haltères posés sur les cuisses. Allonge-toi en les accompagnant vers la poitrine (bascule arrière d\'un bloc), genoux pliés, pieds au sol.','Coudes à ~45° du corps, pousse les haltères à la verticale en soufflant, jusqu\'à bras tendus, sans cambrer.','Redescends lentement jusqu\'à ce que les coudes touchent le sol, pause brève, repousse. Pour sortir : ramène les haltères sur les cuisses et redresse-toi d\'un bloc.'],
  vig:'<b>Dos :</b> entre et sors de la position haltères sur les cuisses, jamais bras tendus depuis le sol ; bas du dos plaqué. <b>Épaules :</b> le sol arrête les coudes, l\'humérus ne passe jamais derrière le tronc : c\'est le point sûr de l\'exercice.',
  fig:{a:{hd:[18,84],nk:[28,82],hp:[56,82],kf:[64,66],ff:[76,84],ea:[36,86],ha:[38,70],props:[{t:'db',at:[38,66]}]},b:{hd:[18,84],nk:[28,82],hp:[56,82],kf:[64,66],ff:[76,84],ea:[36,68],ha:[36,54],props:[{t:'db',at:[36,50]}]}},
  fb:'pompes-inclinees'},
 'tractions-assistees':{nom:'Tractions assistées (supination)',en:'Band-assisted chin-ups',mus:'Dos (grand dorsal), biceps',type:'reps',start:12,inc:1,series:'3 séries de 4, élastique sous le pied ou le genou',
  desc:['Élastique passé sur la barre, pied ou genou dedans. Prise en supination (paumes vers toi), largeur épaules.','Tire jusqu\'à amener le menton au niveau de la barre, coudes vers le bas, souffle en tirant.','Descends lentement en 2-3 s, bras presque tendus en bas.'],
  vig:'<b>Épaules :</b> descends contrôlé, ne te laisse jamais tomber en bas du mouvement. <b>Cou :</b> ne tends pas le menton vers la barre.',
  fin:'le menton qui ne passe plus franchement, ou le corps qui se balance pour l\'y amener. Une traction tirée au balancier n\'est plus une traction.',
  fig:{a:{hd:[60,38],nk:[60,47],hp:[60,68],kf:[56,80],ff:[58,90],ea:[50,36],ha:[48,25],eb:[70,36],hb:[72,25],props:[{t:'bar',at:[30,25],to:[90,25]},{t:'band',at:[60,25],to:[58,90]}],gnd:false},b:{hd:[60,50],nk:[60,59],hp:[60,78],kf:[56,86],ff:[58,94],ea:[52,44],ha:[48,25],eb:[68,44],hb:[72,25],props:[{t:'bar',at:[30,25],to:[90,25]},{t:'band',at:[60,25],to:[58,94]}],gnd:false}},
  fb:'rowing-elastique'},
 'tractions-strictes':{nom:'Tractions strictes',en:'Chin-ups',mus:'Dos, biceps',type:'reps',start:6,inc:1,series:'Séries courtes, qualité maximale',lock:{after:'tractions-assistees',cond:'Atteins 24 tractions assistées (3×8) avec ton élastique le plus fin',need:24},
  desc:['Même mouvement que la version assistée, sans élastique.','Chaque rép complète : bras tendus en bas, menton à la barre en haut. Souffle en tirant, inspire pendant la descente.'],
  vig:'Grosse fierté à débloquer. Reste strict : pas de balancier.',
  fig:{a:{hd:[60,38],nk:[60,47],hp:[60,68],kf:[56,80],ff:[58,90],ea:[50,36],ha:[48,25],eb:[70,36],hb:[72,25],props:[{t:'bar',at:[30,25],to:[90,25]}],gnd:false},b:{hd:[60,52],nk:[60,61],hp:[60,80],kf:[56,88],ff:[58,96],ea:[52,46],ha:[48,25],eb:[68,46],hb:[72,25],props:[{t:'bar',at:[30,25],to:[90,25]}],gnd:false}}},
 'rowing-kettlebell':{nom:'Rowing kettlebell unilatéral',en:'One-arm KB row',mus:'Dos (milieu), arrière d\'épaule',type:'repsSide',start:20,inc:2,series:'2 séries de 10 par côté, avec ta kettlebell de 10 kg',
  desc:['Main et genou gauches en appui sur une chaise ou un banc, dos plat comme une table.','Kettlebell dans la main droite, bras tendu vers le sol.','Tire la kettlebell vers ta hanche (pas vers l\'épaule), coude près du corps, souffle en tirant, puis redescends lentement. Change de côté.'],
  vig:'<b>Dos :</b> l\'appui sur la chaise protège tes lombaires : ne fais jamais cet exercice sans appui. Dos neutre, regard vers le sol.',
  fig:{a:{hd:[20,36],nk:[32,42],hp:[64,46],kf:[68,66],ff:[66,91],kb:[76,64],fb:[84,91],ea:[26,52],ha:[22,62],eb:[44,56],hb:[46,70],props:[{t:'box',at:[12,62],w:20,h:31},{t:'kb',at:[46,70]}]},b:{hd:[20,36],nk:[32,42],hp:[64,46],kf:[68,66],ff:[66,91],kb:[76,64],fb:[84,91],ea:[26,52],ha:[22,62],eb:[48,48],hb:[56,46],props:[{t:'box',at:[12,62],w:20,h:31},{t:'kb',at:[56,46]}]}},
  fb:'rowing-elastique'},
 'rowing-elastique':{nom:'Rowing élastique assis',en:'Seated band row',mus:'Dos (milieu)',type:'reps',start:30,inc:2,series:'3 séries, tension au choix',
  desc:['Assis au sol jambes semi-tendues, élastique passé autour des pieds.','Dos droit, tire les poignées vers le ventre en serrant les omoplates, souffle en tirant.','Reviens lentement sans laisser le dos s\'arrondir.'],
  vig:'<b>Dos :</b> si tenir le dos droit assis au sol est inconfortable, assieds-toi sur un coussin.',
  fig:{a:{hd:[38,42],nk:[42,52],hp:[46,74],kf:[66,68],ff:[86,72],ea:[54,60],ha:[64,62],props:[{t:'band',at:[64,62],to:[86,70]}]},b:{hd:[34,40],nk:[38,50],hp:[46,74],kf:[66,68],ff:[86,72],ea:[46,62],ha:[46,66],props:[{t:'band',at:[46,66],to:[86,70]}]}},
 },
 'curls-halteres':{nom:'Curls haltères',en:'Biceps curls',mus:'Biceps',type:'reps',start:30,inc:2,series:'3 séries de 10, charge max dispo',
  desc:['Debout, haltères le long du corps, paumes vers l\'avant.','Plie les coudes pour monter les haltères vers les épaules en soufflant, coudes fixes contre le corps.','Descends lentement en 2-3 s.'],
  vig:'Ne balance pas le buste pour tricher : si tu dois te cambrer, la charge est trop lourde pour la fin de série.',
  fig:{a:{hd:[60,22],nk:[60,32],hp:[60,58],kf:[54,75],ff:[52,91],kb:[66,75],fb:[68,91],ea:[50,44],ha:[48,56],eb:[70,44],hb:[72,56],props:[{t:'db',at:[47,58]},{t:'db',at:[73,58]}]},b:{hd:[60,22],nk:[60,32],hp:[60,58],kf:[54,75],ff:[52,91],kb:[66,75],fb:[68,91],ea:[50,44],ha:[52,32],eb:[70,44],hb:[68,32],props:[{t:'db',at:[52,30]},{t:'db',at:[68,30]}]}}},
 'goblet-squat':{nom:'Goblet squat',en:'Goblet squat',mus:'Cuisses, fessiers, gainage',type:'reps',start:24,inc:2,series:'3 séries de 8, kettlebell contre la poitrine',
  desc:['Debout pieds largeur épaules, pointes légèrement ouvertes, kettlebell tenue à deux mains contre la poitrine.','Descends en poussant les hanches en arrière et en pliant les genoux, buste fier.','Descends seulement tant que le bas du dos reste plat, puis remonte en poussant dans les talons et en soufflant.'],
  vig:'<b>Dos :</b> arrête la descente avant que le bassin bascule (bas du dos qui s\'arrondit). <b>Genoux :</b> alignés avec les pointes de pieds, amplitude indolore uniquement.',
  fig:{a:{hd:[58,22],nk:[58,32],hp:[58,58],kf:[54,74],ff:[52,91],kb:[64,74],fb:[68,91],ea:[52,40],ha:[54,44],props:[{t:'kb',at:[56,38]}]},b:{hd:[52,40],nk:[54,49],hp:[62,68],kf:[50,74],ff:[50,91],kb:[70,76],fb:[70,91],ea:[48,56],ha:[50,58],props:[{t:'kb',at:[52,52]}]}},
  fb:'box-squat'},
 'box-squat':{nom:'Squat sur chaise',en:'Box squat',mus:'Cuisses, fessiers',type:'reps',start:24,inc:2,series:'3 séries, poids du corps',
  desc:['Debout devant une chaise, bras tendus devant toi.','Descends jusqu\'à effleurer l\'assise (sans t\'asseoir complètement), puis remonte en soufflant.','La chaise garantit une profondeur constante et sûre.'],
  vig:'Version de repli genoux/dos. Contrôle la descente, ne te laisse pas tomber.',
  fig:{a:{hd:[50,22],nk:[50,32],hp:[50,58],kf:[46,74],ff:[44,91],kb:[56,74],fb:[60,91],ea:[58,40],ha:[66,42],props:[{t:'box',at:[62,66],w:24,h:27}]},b:{hd:[42,40],nk:[46,49],hp:[56,66],kf:[44,72],ff:[44,91],kb:[64,74],fb:[64,91],ea:[54,54],ha:[64,52],props:[{t:'box',at:[62,66],w:24,h:27}]}}},
 'fentes-arriere':{nom:'Fentes arrière',en:'Reverse lunges',mus:'Cuisses, fessiers, équilibre',type:'repsSide',start:16,inc:2,series:'2 séries de 8 par jambe',
  desc:['Debout, fais un grand pas en arrière et descends le genou arrière vers le sol.','Le genou avant reste au-dessus de la cheville, buste droit.','Pousse sur la jambe avant pour revenir debout en soufflant. Alterne.'],
  vig:'<b>Genoux :</b> la fente arrière est plus douce que la fente avant, mais reste dans une amplitude sans douleur. Tiens-toi à un meuble si l\'équilibre est instable.',
  fig:{a:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[52,75],ff:[50,91],kb:[62,75],fb:[66,91],ea:[62,42],ha:[64,52]},b:{hd:[50,30],nk:[50,40],hp:[52,64],kf:[42,74],ff:[42,91],kb:[68,80],fb:[80,91],ea:[56,50],ha:[58,58]}},
 fb:'step-ups-bas'},
 'fentes-arriere-lestee':{nom:'Fentes arrière lestées',en:'Weighted reverse lunges',mus:'Cuisses, fessiers, équilibre',type:'repsSide',start:16,inc:2,series:'2 séries de 8 par jambe',
  desc:['Un haltère dans chaque main, bras le long du corps, épaules basses et en arrière.','Grand pas en arrière, genou arrière vers le sol, genou avant au-dessus de la cheville, buste droit.','Pousse sur la jambe avant pour revenir debout en soufflant. Alterne.'],
  vig:'<b>Dos :</b> les bras pendent, la charge reste le long du corps : ne la laisse jamais tirer le buste vers l\'avant. <b>Équilibre :</b> les mains étant prises, un déséquilibre ne se rattrape plus. Reste sur un sol dégagé, et si la ligne vacille, repose les haltères plutôt que de finir la série. <b>Genoux :</b> même amplitude sans douleur qu\'au poids du corps.',
  fb:'fentes-arriere'},
 'step-ups':{nom:'Step-ups sur marchepied',en:'Step-ups',mus:'Cuisses, fessiers',
  desc:['Devant un marchepied qui arrive juste sous le genou, pose un pied entier dessus, orteils dans l\'axe.','Monte en poussant uniquement sur la jambe posée dessus, sans élan, en soufflant.','Redescends lentement sur la même jambe jusqu\'à effleurer le sol, puis remonte sans marquer d\'arrêt.'],
  vig:'<b>Genoux :</b> tout le travail vient de la jambe du dessus. Si la pointe du pied resté au sol pousse pour t\'aider, la série ne mesure plus rien : elle doit effleurer à peine, ou ne pas toucher du tout. Garde le genou dans l\'axe du pied, jamais rentré vers l\'intérieur.',
  fig:{a:{hd:[44,20],nk:[44,30],hp:[44,56],kf:[52,60],ff:[62,63],kb:[40,72],fb:[38,91],ea:[50,42],ha:[54,50],props:[{t:'box',at:[54,63],w:26,h:30}]},b:{hd:[60,6],nk:[60,16],hp:[60,42],kf:[56,54],ff:[62,63],kb:[68,54],fb:[70,66],ea:[66,26],ha:[70,34],props:[{t:'box',at:[54,63],w:26,h:30}]}},
  fb:'step-ups-bas'},
 'step-ups-bas':{nom:'Step-ups sur marche basse',en:'Low step-ups',mus:'Cuisses, fessiers',
  desc:['Devant une marche d\'escalier ou un marchepied bas, pose un pied entier dessus, orteils dans l\'axe.','Monte en poussant sur cette jambe en soufflant, sans élan, puis redescends lentement en contrôlant.','Le pied resté au sol ne sert qu\'à l\'équilibre : il effleure, il ne pousse pas.'],
  vig:'<b>Genoux :</b> version qui ménage les genoux, hauteur faible et descente contrôlée. Garde le genou dans l\'axe du pied, jamais rentré vers l\'intérieur, et tiens-toi à un mur si l\'équilibre est instable.',
  fig:{a:{hd:[46,26],nk:[46,36],hp:[46,60],kf:[52,68],ff:[60,74],kb:[42,76],fb:[40,91],ea:[52,46],ha:[56,54],props:[{t:'box',at:[54,74],w:26,h:19}]},b:{hd:[60,12],nk:[60,22],hp:[60,46],kf:[56,60],ff:[60,74],kb:[66,62],fb:[68,74],ea:[66,32],ha:[70,40],props:[{t:'box',at:[54,74],w:26,h:19}]}}},
 'retraction-scapulaire':{nom:'Rétraction d\'omoplates au sol',en:'Prone scapular retraction',mus:'Fixateurs d\'omoplates, arrière d\'épaules',
  desc:['À plat ventre, front posé au sol, bras écartés en croix reposant au sol, épaules relâchées.','Sans décoller la poitrine, plie les coudes en les tirant vers l\'arrière et vers le bas : les mains décollent de quelques centimètres et les omoplates se serrent l\'une vers l\'autre.','Tiens une seconde en serrant, souffle, puis relâche lentement.'],
  vig:'<b>Dos :</b> la poitrine ne quitte jamais le sol. Dès qu\'elle se soulève, ce n\'est plus une rétraction mais une extension lombaire, et l\'exercice sort de ce que le catalogue autorise. L\'amplitude est petite, c\'est normal : tout le travail est dans le serrage des omoplates.',
  fig:{a:{hd:[28,84],nk:[36,86],hp:[68,88],kf:[82,88],ff:[96,90],ea:[44,90],ha:[52,92]},b:{hd:[28,84],nk:[36,86],hp:[68,88],kf:[82,88],ff:[96,90],ea:[46,86],ha:[38,82]}}},
 'ecartement-elastique':{nom:'Écartement à l\'élastique',en:'Band pull-apart',mus:'Arrière d\'épaules, fixateurs d\'omoplates',
  desc:['Debout, une extrémité de l\'élastique dans chaque main, bras tendus devant toi à hauteur de poitrine, mains écartées de la largeur des épaules.','Ouvre les bras vers l\'extérieur et vers l\'arrière jusqu\'à former une croix, en soufflant, sans jamais plier les coudes.','Reviens lentement en 2 à 3 s en retenant l\'élastique.'],
  vig:'<b>Épaules :</b> les coudes restent verrouillés du début à la fin. Dès qu\'ils se plient, ce sont les triceps qui allongent l\'élastique et l\'arrière d\'épaule reçoit moins. Épaules basses, ne hausse pas les trapèzes.',
  fig:{a:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[52,74],ff:[50,91],kb:[60,74],fb:[62,91],ea:[52,42],ha:[50,44],eb:[60,42],hb:[62,44],props:[{t:'band',at:[50,44],to:[62,44]}]},b:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[52,74],ff:[50,91],kb:[60,74],fb:[62,91],ea:[44,40],ha:[30,40],eb:[68,40],hb:[82,40],props:[{t:'band',at:[30,40],to:[82,40]}]}}},
 'tirage-vertical-elastique':{nom:'Tirage vertical à l\'élastique',en:'Band lat pulldown',mus:'Dos (grand dorsal), biceps',
  desc:['À genoux face à la porte, un peu en avant de l\'ancrage placé en haut de porte, bras tendus vers le haut, les deux mains sur l\'élastique.','Tire vers le bas en pliant les coudes et en les ramenant près des côtes, l\'élastique descendant devant ton visage, jusqu\'à ce que les mains arrivent devant la poitrine. Souffle en tirant.','Remonte lentement en retenant l\'élastique, sans laisser les épaules monter aux oreilles.'],
  vig:'<b>Cou :</b> l\'élastique passe devant le visage, jamais derrière la nuque. Buste droit, ne te penche pas en arrière pour tricher.',
  fig:{a:{hd:[56,24],nk:[56,34],hp:[56,60],kf:[50,80],ff:[66,88],ea:[54,22],ha:[52,10],props:[{t:'band',at:[52,10],to:[38,4]}]},b:{hd:[56,24],nk:[56,34],hp:[56,60],kf:[50,80],ff:[66,88],ea:[62,44],ha:[54,40],props:[{t:'band',at:[54,40],to:[38,4]}]}}},
 'elevations-laterales-elastique':{nom:'Élévations latérales à l\'élastique',en:'Band lateral raises',mus:'Épaules (deltoïdes)',
  desc:['Debout, les deux pieds sur le milieu de l\'élastique écartés de la largeur des hanches, une extrémité dans chaque main le long du corps, coudes très légèrement fléchis.','Monte les bras sur les côtés en soufflant, jusqu\'à l\'horizontale, pas plus haut, en 2 s.','Redescends lentement en 2 à 3 s : c\'est la descente qui travaille le plus.'],
  vig:'<b>Épaules :</b> épaules basses, ne hausse pas les trapèzes. Si ça tire dans le cou, réduis l\'amplitude ou prends un niveau plus faible.',
  fig:{a:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[48,74],ff:[46,91],kb:[64,74],fb:[66,91],ea:[48,46],ha:[46,58],eb:[64,46],hb:[66,58],props:[{t:'band',at:[46,58],to:[46,91]},{t:'band',at:[66,58],to:[66,91]}]},b:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[48,74],ff:[46,91],kb:[64,74],fb:[66,91],ea:[42,38],ha:[28,38],eb:[70,38],hb:[84,38],props:[{t:'band',at:[28,38],to:[46,91]},{t:'band',at:[84,38],to:[66,91]}]}}},
 'curls-elastique':{nom:'Curls à l\'élastique',en:'Band curls',mus:'Biceps',
  desc:['Debout, les deux pieds sur le milieu de l\'élastique, une extrémité dans chaque main le long du corps, paumes vers l\'avant.','Plie les coudes pour monter les mains vers les épaules en soufflant, coudes fixes contre le corps.','Descends lentement en 2 à 3 s.'],
  vig:'<b>Dos :</b> ne balance pas le buste pour tricher. Si tu dois te cambrer, le niveau est trop fort pour la fin de série.',
  fig:{a:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[48,74],ff:[46,91],kb:[64,74],fb:[66,91],ea:[48,46],ha:[46,58],eb:[64,46],hb:[66,58],props:[{t:'band',at:[46,58],to:[46,91]},{t:'band',at:[66,58],to:[66,91]}]},b:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[48,74],ff:[46,91],kb:[64,74],fb:[66,91],ea:[48,46],ha:[50,34],eb:[64,46],hb:[62,34],props:[{t:'band',at:[50,34],to:[46,91]},{t:'band',at:[62,34],to:[66,91]}]}}},
 'rdl-elastique':{nom:'Soulevé de terre roumain à l\'élastique',en:'Band Romanian deadlift',mus:'Ischio-jambiers, fessiers',
  desc:['Debout, les deux pieds sur le milieu de l\'élastique, une extrémité dans chaque main devant les cuisses, dos parfaitement plat.','Pousse les hanches en arrière, genoux à peine fléchis, les mains glissent le long des jambes.','Descends jusqu\'à sentir l\'étirement derrière les cuisses, puis remonte en serrant les fessiers et en soufflant.'],
  vig:'<b>Dos :</b> le dos reste plat du bassin à la nuque, le mouvement vient des hanches et jamais de la colonne. Nuque dans le prolongement, ne relève pas le menton.',
  fig:{a:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[54,75],ff:[52,91],ea:[54,44],ha:[54,56],props:[{t:'band',at:[54,56],to:[52,91]}]},b:{hd:[30,44],nk:[38,48],hp:[62,56],kf:[58,74],ff:[54,91],ea:[42,60],ha:[44,72],props:[{t:'band',at:[44,72],to:[54,91]}]}}},
 'mollets-debout':{nom:'Mollets debout',en:'Calf raises',mus:'Mollets',type:'reps',start:40,inc:5,series:'2 séries de 20, tiens-toi à un mur',
  desc:['L\'avant du pied sur l\'arête d\'une marche, talons dans le vide, une main au mur pour l\'équilibre.','Laisse descendre les talons sous le niveau de la marche jusqu\'à la fin de l\'étirement, jambes tendues.','Monte sur la pointe le plus haut possible, marque un temps en haut en soufflant, redescends lentement.'],
  vig:'<b>Amplitude :</b> c\'est la moitié basse qui fait le travail. Sans marche l\'exercice se fait quand même, talons au sol, mais tu perds la descente sous l\'horizontale et l\'essentiel avec. La bonne hauteur est celle où le talon arrive en fin d\'étirement sans toucher le sol, en général 7 à 10 cm : au-delà c\'est la cheville qui limite, pas la marche. <b>Équilibre :</b> les doigts au mur guident, ils ne portent pas.',
  fig:{a:{hd:[56,24],nk:[56,34],hp:[56,60],kf:[52,76],ff:[50,91],kb:[60,76],fb:[62,91],ea:[48,44],ha:[42,40],props:[{t:'bar',at:[36,20],to:[36,90]}]},b:{hd:[56,18],nk:[56,28],hp:[56,54],kf:[52,72],ff:[50,87],kb:[60,72],fb:[62,87],ea:[48,38],ha:[42,36],props:[{t:'bar',at:[36,20],to:[36,90]}]}}},
 'mollets-debout-leste':{nom:'Mollets debout lestés',en:'Weighted calf raises',mus:'Mollets',type:'reps',start:40,inc:5,series:'2 séries de 12, sac sur le dos',
  desc:['Sac à dos chargé, sangles serrées pour que la charge ne balance pas, l\'avant du pied sur l\'arête de la marche.','Talons dans le vide, descente complète jusqu\'à la fin de l\'étirement, jambes tendues.','Monte sur la pointe, temps d\'arrêt en haut en soufflant, redescente lente et contrôlée.'],
  vig:'<b>Dos :</b> la charge est portée en compression sur le rachis. Sangles serrées, buste droit, jamais de rebond en bas ni de balancement du sac. Si le bas du dos parle, repose le sac et finis au poids du corps. <b>Charge :</b> disques, kettlebell, bouteilles pleines, peu importe la forme, seul le total compte.',
  fb:'mollets-debout'},
 'mollets-une-jambe':{nom:'Mollets sur une jambe',en:'Single-leg calf raises',mus:'Mollets',type:'repsSide',start:16,inc:2,series:'2 séries de 8 par jambe',
  desc:['L\'avant d\'un seul pied sur l\'arête de la marche, l\'autre jambe fléchie en arrière, doigts au mur pour l\'équilibre.','Laisse descendre le talon sous le niveau de la marche jusqu\'à la fin de l\'étirement, jambe tendue.','Monte sur la pointe le plus haut possible en soufflant, redescends lentement. Fais toutes les répétitions d\'un côté, puis l\'autre.'],
  vig:'<b>Équilibre :</b> les doigts au mur guident, ils ne portent pas : si la main pousse, la série ne mesure plus rien. <b>Cheville :</b> le mollet porte ici tout le poids du corps, deux fois plus qu\'à deux jambes. Descends progressivement dans l\'étirement les premières séances plutôt que d\'aller au bout d\'emblée.',
  fb:'mollets-debout'},
 'mollets-une-jambe-leste':{nom:'Mollets sur une jambe lestés',en:'Weighted single-leg calf raises',mus:'Mollets',type:'repsSide',start:16,inc:2,series:'2 séries de 8 par jambe, sac sur le dos',
  desc:['Sac à dos chargé et sanglé, l\'avant d\'un seul pied sur l\'arête de la marche, l\'autre jambe fléchie en arrière.','Doigts au mur, descente complète du talon sous la marche, jambe tendue.','Monte sur la pointe en soufflant, redescends lentement. Tout un côté, puis l\'autre.'],
  vig:'<b>Dos :</b> charge en compression sur le rachis, sangles serrées, buste droit, aucun rebond en bas. <b>Équilibre :</b> les deux mains restent libres, c\'est la raison du sac plutôt que d\'un poids tenu. Si la ligne vacille, repose le sac plutôt que de finir la série.',
  fb:'mollets-debout'},
 'rdl-kettlebell':{nom:'Soulevé de terre roumain KB',en:'KB Romanian deadlift',mus:'Ischios, fessiers, bas du dos',type:'reps',start:20,inc:2,series:'3 séries lentes',lock:{after:'goblet-squat',cond:'Fais {n} séries de 15 goblet squats',need:15,minSets:2},
  desc:['Debout, kettlebell tenue à deux mains devant les cuisses.','Pousse les hanches en arrière, dos parfaitement plat, genoux à peine fléchis : la KB glisse le long des jambes.','Descends jusqu\'à sentir l\'étirement derrière les cuisses, puis remonte en serrant les fessiers et en soufflant.'],
  vig:'<b>Dos :</b> exercice débloqué car excellent pour renforcer la chaîne postérieure, MAIS le dos plat est non négociable. Filme-toi de profil les premières fois.',
  fig:{a:{hd:[56,22],nk:[56,32],hp:[56,58],kf:[54,75],ff:[52,91],kb:[60,75],fb:[62,91],ea:[54,44],ha:[54,54],props:[{t:'kb',at:[54,56]}]},b:{hd:[30,44],nk:[38,48],hp:[62,56],kf:[58,74],ff:[54,91],ea:[40,60],ha:[42,70],props:[{t:'kb',at:[42,72]}]}}},
 'bird-dog':{nom:'Bird-dog',en:'Bird-dog',mus:'Gainage profond, bas du dos',type:'repsSide',start:16,inc:2,series:'2 séries de tenues par côté, rythmées au son',
  desc:['À quatre pattes, mains sous les épaules, genoux sous les hanches, dos neutre.','Au bip aigu, tends en même temps le bras droit devant et la jambe gauche derrière, à l\'horizontale.','Tiens jusqu\'au bip grave en respirant, sans bouger le bassin ; reviens, et change de côté au bip suivant. La position de retour est un repos.'],
  vig:'<b>Dos :</b> exercice de référence pour les lombaires fragiles. Le bassin ne doit pas tourner : imagine un verre d\'eau posé sur tes reins.',
  fig:{a:{hd:[24,50],nk:[34,54],hp:[70,54],kf:[70,72],ff:[70,90],ea:[34,72],ha:[34,90]},b:{hd:[18,46],nk:[28,52],hp:[66,52],kf:[66,70],ff:[66,90],ea:[16,50],ha:[6,48],kb:[86,52],fb:[102,50]}},
 },
 'planche':{nom:'Planche',en:'Plank',mus:'Gainage complet',type:'temps',start:25,inc:5,series:'Meilleure tenue du jour, 2 essais possibles',
  desc:['En appui sur les avant-bras et les pointes de pieds, corps aligné des épaules aux talons.','Serre abdos et fessiers.','Le chrono s\'arrête dès que le bassin monte ou descend.'],
  vig:'<b>Dos :</b> un bassin qui s\'affaisse creuse les lombaires : mieux vaut 20 s parfaites que 60 s tordues. <b>Cou :</b> regard au sol, nuque longue. <b>Respiration :</b> ne bloque jamais, c\'est le réflexe naturel en gainage et il fait grimper la tension. Souffle lentement, le chrono continue.',
  fin:'le bassin qui monte ou qui descend. C\'est aussi ce qui arrête le chrono : la mesure et le critère sont le même.',
  fig:{a:{hd:[22,58],nk:[32,62],hp:[66,66],kf:[84,70],ff:[102,90],ea:[34,76],ha:[24,88]},b:{hd:[22,58],nk:[32,62],hp:[66,66],kf:[84,70],ff:[102,90],ea:[34,76],ha:[24,88]}},
  fb:'planche-genoux'},
 'planche-genoux':{nom:'Planche sur genoux',en:'Knee plank',mus:'Gainage',type:'temps',start:30,inc:5,series:'Meilleure tenue du jour',
  desc:['Même position que la planche, mais en appui sur les genoux.','Ligne droite des épaules aux genoux.'],
  vig:'Version de repli : parfaite pour construire le gainage sans surcharger. <b>Respiration :</b> ne bloque jamais, souffle lentement pendant la tenue.',
  fig:{a:{hd:[24,60],nk:[34,64],hp:[66,68],kf:[80,78],ff:[94,74],ea:[36,78],ha:[26,90]},b:{hd:[24,60],nk:[34,64],hp:[66,68],kf:[80,78],ff:[94,74],ea:[36,78],ha:[26,90]}}},
 'dead-bug':{nom:'Dead bug',en:'Dead bug',mus:'Abdos profonds',type:'reps',start:20,inc:2,series:'2 séries de tenues par côté, rythmées au son',
  desc:['Allongé sur le dos, bras tendus vers le plafond, hanches et genoux à 90°.','Au bip aigu, souffle en tendant le bras droit derrière la tête et la jambe gauche vers le sol, sans les poser : c\'est l\'expiration qui garde les côtes basses et le dos plaqué. Tiens jusqu\'au bip grave.','Le bas du dos reste plaqué au sol en permanence. Reviens, alterne au bip suivant : la position de retour reste chargée, toute la série est sous tension.'],
  vig:'<b>Dos :</b> si le bas du dos décolle, réduis l\'amplitude. C\'est l\'anti-crunch : tout le bénéfice, zéro compression lombaire. <b>Souffle :</b> à 3 s, une expiration par tenue ; à 6 et 10 s, inspire par le nez en tenue sans lever les côtes, expire long, ne bloque jamais. Si ce sont les fléchisseurs de hanche qui brûlent et non le ventre, raccourcis le levier ou plie le genou.',
  fin:'le bas du dos qui décolle du sol. Dès que les lombaires se creusent, la série est finie, quel que soit le compte.',
  fig:{a:{hd:[20,84],nk:[30,82],hp:[58,82],kf:[62,64],ff:[76,66],ea:[34,66],ha:[36,54]},b:{hd:[20,84],nk:[30,82],hp:[58,82],kf:[70,74],ff:[86,80],ea:[24,68],ha:[12,66]}},
 },
 'pallof-press':{nom:'Pallof press',en:'Pallof press',mus:'Obliques, anti-rotation',type:'repsSide',start:16,inc:2,series:'2 séries de 8 par côté',
  desc:['Élastique fixé à hauteur de poitrine sur le côté (ancrage de porte), tenu à deux mains contre le sternum.','Tends les bras devant toi : l\'élastique essaie de te faire pivoter, résiste.','Souffle en tendant les bras, respire pendant les 2 s sans bloquer, reviens. Fais l\'autre côté.'],
  vig:'<b>Dos :</b> excellent gainage anti-rotation sans aucune flexion de colonne.',
  fin:'le tronc qui pivote vers l\'ancrage. L\'exercice est un anti-mouvement : dès que tu tournes, il n\'y a plus d\'exercice.',
  fig:{a:{hd:[52,24],nk:[52,34],hp:[52,60],kf:[46,76],ff:[44,91],kb:[58,76],fb:[62,91],ea:[60,44],ha:[56,42],props:[{t:'band',at:[56,42],to:[104,36]}]},b:{hd:[52,24],nk:[52,34],hp:[52,60],kf:[46,76],ff:[44,91],kb:[58,76],fb:[62,91],ea:[64,40],ha:[76,40],props:[{t:'band',at:[76,40],to:[104,36]}]}}},
 'cardio-bas-impact':{nom:'Intervalles bas impact',en:'Low-impact intervals',mus:'Cardio, jambes',type:'circuit',start:8,inc:1,
  phases:[{l:'Montées de genoux (sans saut)',s:30},{l:'Marche rapide sur place',s:30}],
  desc:['Alterne 30 s de montées de genoux dynamiques SANS sauter (un pied toujours au sol) et 30 s de marche rapide de récupération.','Bras actifs, rythme qui essouffle sans mettre dans le rouge.','La cible augmente de 1 round au fil des semaines.'],
  vig:'<b>Genoux :</b> zéro impact tant qu\'ils sont sensibles : ne saute pas, même si l\'envie vient.',
  fig:{a:{hd:[56,20],nk:[56,30],hp:[56,56],kf:[50,64],ff:[54,74],kb:[60,74],fb:[62,91],ea:[62,42],ha:[68,36]},b:{hd:[56,20],nk:[56,30],hp:[56,56],kf:[62,64],ff:[58,74],kb:[52,74],fb:[50,91],ea:[50,42],ha:[44,36]}},
  fb:'marche-continue'},
 'marche-continue':{nom:'Marche rapide continue',en:'Brisk walk-in-place',mus:'Cardio doux',type:'circuit',start:1,inc:0,phases:[{l:'Marche rapide sur place',s:240}],
  desc:['4 minutes de marche rapide sur place, bras actifs, respiration ample.'],
  vig:'Version de repli : garder le corps en mouvement, sans stress articulaire.',
  fig:{a:{hd:[56,20],nk:[56,30],hp:[56,56],kf:[50,68],ff:[50,84],kb:[62,72],fb:[64,91],ea:[62,42],ha:[66,48]},b:{hd:[56,20],nk:[56,30],hp:[56,56],kf:[62,68],ff:[62,84],kb:[50,72],fb:[48,91],ea:[50,42],ha:[46,48]}}},
 'kb-swings':{nom:'Kettlebell swings',en:'KB swings',mus:'Fessiers, ischios, cardio',type:'reps',start:30,inc:5,series:'3 séries de 10, explosif mais propre',lock:{after:'rdl-kettlebell',cond:'Fais {n} séries de 15 soulevés roumains : le swing est le même geste, en dynamique',need:15,minSets:2},
  desc:['Même charnière de hanche que le soulevé roumain : la KB passe entre les jambes, dos plat.','Propulse la KB à hauteur de poitrine par une extension explosive des hanches (pas des bras), souffle sec à chaque projection, inspire pendant la descente.','Laisse-la redescendre en te penchant, hanches en arrière.'],
  vig:'<b>Dos :</b> le swing est excellent pour la chaîne postérieure UNIQUEMENT avec un dos plat verrouillé. Le geste vient des hanches, jamais des lombaires. <b>Lestes :</b> mouvement balistique, vérifie le serrage des scratchs avant chaque série.',
  fig:{a:{hd:[36,40],nk:[42,46],hp:[62,54],kf:[58,72],ff:[54,91],kb:[66,74],fb:[68,91],ea:[46,58],ha:[52,68],props:[{t:'kb',at:[54,70]}]},b:{hd:[54,20],nk:[54,30],hp:[56,56],kf:[52,74],ff:[50,91],kb:[60,74],fb:[62,91],ea:[54,38],ha:[66,36],props:[{t:'kb',at:[70,34]}]}}},
 'etir-nuque':{nom:'Étirement nuque',en:'Neck stretch',mus:'Cou, trapèzes',type:'stretch',dur:40,bilat:true,
  desc:['Assis ou debout, pose la main du côté vers lequel tu penches sur le dessus de la tête, incline doucement l\'oreille vers l\'épaule, main opposée relâchée vers le sol.','20 s par côté, traction très douce, jamais de douleur. Souffle lentement, c\'est l\'expiration qui fait céder le muscle.'],
  vig:'<b>Cou :</b> aucune force, on cherche un étirement confortable, pas un record.',
  fig:{a:{hd:[54,24],nk:[58,34],hp:[58,60],kf:[52,76],ff:[50,91],kb:[64,76],fb:[66,91],ea:[66,46],ha:[70,58]},b:{hd:[64,26],nk:[58,34],hp:[58,60],kf:[52,76],ff:[50,91],kb:[64,76],fb:[66,91],ea:[50,46],ha:[46,58]}}},
 'etir-pecs':{nom:'Ouverture pectoraux',en:'Doorway chest stretch',mus:'Pectoraux, avant d\'épaule',type:'stretch',dur:60,bilat:true,
  desc:['Avant-bras contre le chambranle d\'une porte, coude à hauteur d\'épaule.','Avance doucement le buste jusqu\'à sentir l\'ouverture devant l\'épaule. 30 s par côté, en soufflant lentement.'],
  vig:'Contrepoids direct des heures d\'écran. Étirement franc mais jamais douloureux.',
  fig:{a:{hd:[50,24],nk:[52,34],hp:[54,60],kf:[50,76],ff:[48,91],kb:[60,76],fb:[64,91],ea:[66,32],ha:[70,22],props:[{t:'bar',at:[74,14],to:[74,90]}]},b:{hd:[46,24],nk:[48,34],hp:[52,60],kf:[48,76],ff:[46,91],kb:[58,76],fb:[62,91],ea:[64,32],ha:[70,22],props:[{t:'bar',at:[74,14],to:[74,90]}]}}},
 'chat-vache':{nom:'Chat-vache',en:'Cat-cow',mus:'Mobilité colonne',type:'stretch',dur:45,
  desc:['À quatre pattes, alterne lentement dos rond (menton rentré, expire) et dos creusé (regard devant, inspire).','Mouvement fluide, au rythme de la respiration.'],
  vig:'<b>Dos :</b> reste dans une amplitude confortable, surtout côté dos creusé.',
  fig:{a:{hd:[22,56],nk:[32,54],hp:[70,54],kf:[70,72],ff:[70,90],ea:[32,72],ha:[32,90]},b:{hd:[22,46],nk:[32,52],hp:[70,52],kf:[70,72],ff:[70,90],ea:[32,72],ha:[32,90]}}},
 'etir-hanches':{nom:'Étirement fléchisseurs de hanche',en:'Hip flexor stretch',mus:'Avant de hanche, psoas',type:'stretch',dur:60,bilat:true,
  desc:['En fente, genou arrière posé au sol (coussin dessous).','Avance doucement le bassin en serrant le fessier arrière, buste droit. 30 s par côté, en soufflant lentement.'],
  vig:'<b>Dos :</b> ne creuse pas les lombaires : le mouvement vient du bassin qui avance.',
  fig:{a:{hd:[52,26],nk:[52,36],hp:[52,62],kf:[64,70],ff:[66,90],kb:[38,78],fb:[24,84],ea:[58,48],ha:[60,58]},b:{hd:[56,26],nk:[56,36],hp:[56,62],kf:[68,70],ff:[68,90],kb:[42,80],fb:[26,86],ea:[62,48],ha:[64,58]}}},
 'etir-ischios':{nom:'Étirement ischios doux',en:'Hamstring stretch',mus:'Arrière de cuisse',type:'stretch',dur:60,bilat:true,
  desc:['Talon posé sur une marche basse, jambe presque tendue.','Penche-toi vers l\'avant DEPUIS les hanches, dos plat, jusqu\'à l\'étirement. 30 s par jambe, en soufflant lentement.'],
  vig:'<b>Dos :</b> dos plat obligatoire : c\'est la bascule du bassin qui étire, pas l\'arrondi du dos.',
  fig:{a:{hd:[42,28],nk:[44,38],hp:[48,62],kf:[44,76],ff:[42,91],kb:[62,70],fb:[76,74],ea:[52,50],ha:[56,60],props:[{t:'box',at:[70,74],w:20,h:19}]},b:{hd:[36,36],nk:[40,44],hp:[48,62],kf:[44,76],ff:[42,91],kb:[62,70],fb:[76,74],ea:[48,56],ha:[54,64],props:[{t:'box',at:[70,74],w:20,h:19}]}}},
 'posture-enfant':{nom:'Posture de l\'enfant',en:'Child\'s pose',mus:'Dos, épaules, détente',type:'stretch',dur:45,
  desc:['À genoux, fesses sur les talons, bras tendus loin devant, front vers le sol.','Respire profondément, laisse le dos s\'allonger.'],
  vig:'Clôture parfaite : détente complète de la colonne.',
  fig:{a:{hd:[22,80],nk:[32,76],hp:[64,72],kf:[74,84],ff:[86,88],ea:[20,84],ha:[8,88]},b:{hd:[22,80],nk:[32,76],hp:[64,72],kf:[74,84],ff:[86,88],ea:[20,84],ha:[8,88]}}}
};

